### ISSUE TITLE
 MODEL_FILENAME = 'digit.pkl' WEIGHTS_FILENAME = 'weights1.h5'

### ISSUE THREAD

**Issue by kashyap32** [Nozdi/digit-ocr#1]
Where can I Find these files?

**Comment by Nozdi** [comment]
Uncomment line: https://github.com/Nozdi/digit-ocr/blob/master/train.py#L132
Run `train.py`.
It's not an issue... Closing ;)

**Comment by kashyap32** [comment]
Sorry!!! My Mistake !!!
